Movement refactor
CVPIA-OSC/fallRunDSM pull request #60
Opened 2023-08-18 20:45 UTC by MaddeeRubenson

addresses the following issue: https://github.com/CVPIA-OSC/fallRunDSM/issues/59

2023-08-21 17:04 UTC, ergz commented on R/model.R
> +    fish_list <- lapply(1:10, function(i) list(juveniles = juveniles,
nice, I like this!

2023-08-21 17:13 UTC, ergz requested changes
looks good! just worth a second look at the dataframe growing part, try out insertion instead of appending. If this becomes too much of a refactor let me know

2023-08-21 17:13 UTC, ergz commented on R/model.R
> +    names(fish_list) <- c(paste0("fish_", 0:9))
let's rename `fish_` to `route_*_fish`

2023-08-21 22:25 UTC, ergz requested changes

2023-08-21 23:33 UTC, MaddeeRubenson commented on R/model.R
> +    names(fish_list) <- c(paste0("fish_", 0:9))
implemented

2023-08-22 18:48 UTC, MaddeeRubenson commented on R/model.R
> +                                       fish_list$fish_0,
`fish_list` is a catalog of the fish (1 - 10) lists . This logic can be implemented but is not necessary the way it's currently set up where the output of `juvenile_month_dynamic` is a direct input into the `create_fish_df` function. We can discuss more tomorrow during our pair.

2023-08-22 19:13 UTC, MaddeeRubenson commented on R/juvenile_month_dynamic.R
> +  tmp <- rbind(fish_df$north_delta_fish, matrix(0, ncol = 4, nrow = 8)) + fish_df$south_delta_fish
implemented

2023-08-23 22:24 UTC, merged